#!/bin/bash

#############################
#                           
#  Math libraries useful for Deep Learning  
#                          
#############################
 
sudo apt-get install -y openmpi-bin
sudo apt-get install -y libprotobuf-dev libleveldb-dev libsnappy-dev libhdf5-serial-dev 
sudo apt-get install -y protobuf-compiler llibopencv-dev libcupti-dev
sudo apt-get install -y --no-install-recommends libboost-all-dev
sudo apt-get install -y libgflags-dev libgoogle-glog-dev liblmdb-dev libblas-dev 
sudo apt-get install -y libatlas-base-dev libopenblas-dev 
sudo apt-get install -y python3-nose python3-numpy python3-scipy
sudo -H pip3 install numpy scipy scikit-learn protobuf


#############################
#
# Tensorflow and friends
#
#############################

# Tensorflow:  GPU version
#sudo -H pip3 install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp35-cp35m-linux_x86_64.whl

# Tensorflow:  CPU only version

sudo -H pip3 install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.4.0-cp35-cp35m-linux_x86_64.whl

# Friends and family
sudo -H pip3 install keras h5py


############################
#
# CNTK
#
############################

# CNTK with GPU
#sudo -H pip3 install https://cntk.ai/PythonWheel/GPU/cntk-2.1-cp35-cp35m-linux_x86_64.whl

# CNTK with CPU only
sudo -H pip3 install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.3-cp35-cp35m-linux_x86_64.whl


############################
# 
# PyTorch
# 
############################

# pytorch:  GPU version
#sudo -H pip3 install http://download.pytorch.org/whl/cu80/torch-0.2.0.post3-cp35-cp35m-manylinux1_x86_64.whl

# pytorch:  CPU only version
sudo -H pip3 install http://download.pytorch.org/whl/cu75/torch-0.2.0.post3-cp35-cp35m-manylinux1_x86_64.whl

sudo -H pip3 install torchvision


