#!/bin/bash

############################
#
# Install NVIDIA Drivers for GPU
# Install CUDA Toolkit
# Install CUDA Deep Neural Network library
#
############################


# 
# Here are the names of the CUDA software we will be installing.
#
cudafilename="cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64.deb"
cudnnfilename="cudnn-8.0-linux-x64-v6.0.tgz"

#
# If CUDA software is not present, cry foul!
#
if [ -f "$cudafilename" ]
then
  echo "Found CUDA toolkit ($cudafilename)... cool."
else
  if [ -f ~/Downloads/$cudafilename ]
  then
    echo "Moving $cudafilename to the current directory."
    mv ~/Downloads/$cudafilename .
  else
    echo " "
    echo "I couldn't find $cudafilename ..."
    echo " "
    echo "You need to download the CUDA toolkit from NVIDIA."
    echo " - Go to https://developer.nvidia.com/cuda-downloads."
    echo " - Scroll down to the bottom and click Legacy Releases."
    echo " - Select the latest CUDA 8.0 GA2 (Feb 2017)."
    echo " - Select Linux, x86_64, Ubuntu, 16.04, deb (local)."
    echo " - Go to Base Installer and click download."
    echo "Then come back here and try again."
    echo " "
    exit
  fi
fi


#
# If CUDA Deep Neural Network library is not present, cry foul!
#
if [ -f "$cudnnfilename" ]
then
  echo "Found CUDA Deep Neural Network library ($cudafilename)... cool."
else
  if [ -f ~/Downloads/$cudnnfilename ]
  then
    echo "Moving $cudnnfilename to the current directory."
    mv ~/Downloads/$cudnnfilename .
  else
    echo " "
    echo "I couldn't find $cudnnfilename ..."
    echo " "
    echo "You need to download the CUDA Deep Neural Network library from NVIDIA."
    echo " - Go to https://developer.nvidia.com/cudnn."
    echo " - Click Download, accept the terms, click on cuDNN v6.0 for CUDA 8.0."
    echo " - Click cuDNN v6.0 Library for Linux."
    echo "Then come back here and try again."
    echo " "
    exit
  fi
fi





echo "Bailing out."
exit
   
  
#
# Out with the old.  
#
sudo apt-get purge nvidia*
sudo apt-get autoremove

#
# In with the new.
#
# nvidia-384 is the stable release as of today (4 December 2017).
# You may want to check here to see if things have moved on:
#    https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa
#
sudo apt-get add-apt-repository ppa:graphics-drivers
sudo apt-get update
sudo apt-get install -y nvidia-384

#
# Ubuntu ships with open source graphics drivers (nouveau).
# These commands will keep them from messing things up.
#
sudo cp blacklist-nouveau.conf /etc/modprobe.d/
echo options nouveau modeset=0 | sudo tee -a /etc/mdprobe.d/nouveau-kms.conf
sudo update-initramfs -u

#
# Installing CUDA Toolkit 8.0
# Although 9.0 is the latest and greatest, Tensorflow 1.4 doesn't
# run with 9.0.
#
sudo dpkg -i $cudafilename
sudo apt-get update
sudo apt-get install -y cuda

#
# Similarly, Tensorflow 1.4 needs cuDNN V6.0
#
tar -xzvf $cudnnfilename
sudo cp cuda/include/cudnn.h /usr/local/cuda/include
sudo cp cuda/lib64/libcudnn* /usr/local/cuda/lib64
sudo chmod a+r /usr/local/cuda/include/cudnn.h /usr/local/cuda/lib64/libcudnn*
rm -rf cuda

#
# Update library paths
#
cat gpu/setpaths.txt >> ~/.bashrc

