#!/bin/bash

############################
#
# Dan's personal stuff
#
############################

cp goodies/*.jpg ~/Pictures/
sudo apt-get install -y chromium-browser hplip-gui gir1.2-gtop-2.0

#
#  Post-install stuff via GUI:
#
#  0.  vino-preferences.  top two options, bottom one, password
#      Allow view; allow control; require pw; never; close
#  1.  Left toolbar.  There is a lot of stuff there that
#      you may want to clear out.  I set it to: chromium,
#      terminal, files, settings, help.
#  2.  Remote access (SSH and remote desktop):  Settings 
#      -> Sharing. Remote Login should have been turned on
#      when you installed openssh.  Turn on Screen Sharing,
#      Allow remote control.  Require PW.  It is a max of
#      8 chars so I just use the first 8 of my logon PW.
#      Now you can SSH to this box by name, or remote 
#      desktop to it using Remmina on another Ubuntu.
#  3.  By default Gnome provides no close/min/max on app
#      windows.  Issue this command to fix:
#      gsettings set org.gnome.desktop.wm.preferences button-layout close,minimize,maximize:
#  
#  Dan-specific setup things:
#
#  1.  Browser.  I use Chrome across all platforms.  Start
#      chromium (OSS version);  log in;  Add to Favorites
#      on left toolbar.
#  2.  Terminal.  Ctrl-Alt-T to start.  Weird albino terminal
#      box.  Edit->Preferences->profiles->edit.  I set it to
#      120x24.  Clicked colours & unchecdd System Theme.
#      Black and green!  Remember the Hazeltine!  Add to 
#      Favorites on the left toolbar. 
#  3.  Files -> Pictures -> wallpaper.  Choose one;  right
#      click;  make it background.
#  4.  Wireless printer:  Settings -> Printer.  It should 
#      find your wireless printer.  Add it and print a
#      test page.
#  5.  System monitor for the top bar.   Browse to
#      extensions.gnome.org/extension/120/system-monitor
#      Use the switch to turn it on.  Click on the tools
#      icon to customize it:  I tick all the boxes along
#      the top;  then go thru each display in turn.  I set
#      CPU, memory, net, and thermal to Display, and turn
#      all others off.  For the Display guys, I set them to
#      Digit (rather than graph).
#  6.  Setting up Dropbox.  I found the command line options
#      for this were problematic;  best to browse to 
#      dropbox.com and do it all there.
#       - Log in.  
#       - Click your pic in upper right; click Install
#       - Choose Ubuntu 64 bit;  when downloaded, Open it.
#       - Click Install (again!).  Eventually a dialog box
#         appears saying "Dropbox Start Required".  Now there
#         will be a flurry of OK-related buttons to push but
#         eventually you will get a Dropbox icon in the lower
#         left showing it's syncing.
#       - Right click that, Pause Syncing, go to Preferences,
#         click Sync (upper right), and select which folders
#         you want sync'd.  Do the OK OK OK thing.
#       - Right click Dropbox icon again and resume sync
#  7.  Calibre setup
#  8.  Turn off touchpad.
#   




