#!/bin/bash

############################
#
# Install no-ip.com dynamic DNS updater.
# Make it auto-start on reboot.
#
############################

sudo cp noip/noip.service /etc/systemd/system/

cd /usr/local/src/
sudo wget http://www.no-ip.com/client/linux/noip-duc-linux.tar.gz
sudo tar xf noip-duc-linux.tar.gz
cd noip-2.1.9-1
sudo make install
sudo chmod 700 /usr/local/bin/noip2
sudo chown root:root /usr/local/bin/noip2
sudo systemctl enable noip
sudo systemctl start noip

